### ISSUE TITLE
支持双开APP的快捷方式

### ISSUE THREAD

**Issue by tiann** [shinado/aris-open#10]
你好，无意中看到这个项目，非常滴酷炫，先赞一个！

回到正题，我是 [VirtualXposed](https://github.com/android-hacker/VirtualXposed) 的开发者，这是一个类似双开的APP，为了使用方便，会把内部的APP通过创建桌面快捷方式让用户能在系统桌面直接打开被双开的APP。

但是目前在 ARIS 中直接搜索，无法找到双开内部的APP。想咨询一下，如果要支持这种方式，我应该如何做？（我可以修改内部逻辑，比如说让ARIS给我发送特定intent？）

（我尝试过 config instant run，但是不知道这个具体是何意思，正在啃代码）

**Comment by Ancientwood** [comment]
`config instant run` 类似于 `Query String` 替换 `{q}` 等关键字来进行直接打开URL搜索之类吧
（我不是开花者这些都是我瞎说的
__你这个类似打开桌面快捷方式的feature我也提过好多次，所以来吐个槽__ (:

**Comment by shinado** [comment]
@tiann 你好，快捷方式马上就会添加支持。

至于instant run，就如Ancientwood所说，最主要的作用是通过拼接URL进行搜索，其次是可以拼接插件。比如如果把translate加入到instant run，就不需要再输入->translate，直接选择即可。但是～因为没有人用，所以已经很久没有维护啦。

**Comment by tiann** [comment]
貌似快捷方式还是有问题，不过我通过另外一种方式解决了。
