### ISSUE TITLE
jget对json的嵌套解析似乎有问题

### ISSUE THREAD

**Issue by Ancientwood** [shinado/aris-open#2]
以教程来说：
`https://api.fixer.io/latest?base=CNY&symbols=USD->post->jget rates->jget usd`
指令输出：
`10:41:48 console.execute ->https://api.fixer.io/latest?base=cny&symbols=usd -> $POST -> $JGET -> https://api.fixer.io/latest?base=cny&symbols=usd->post->jget rates->jget usd`
结果：
`{}https://api.fixer.io/latest?base=cny&symbols=usd->post->jget rates->jget usd`
尝试其他API，能解析第一层

**Comment by shinado** [comment]
谢谢反馈，确实是个bug

**Comment by Ancientwood** [comment]
clipboard内为教程USD`https://api.fixer.io/latest?base=CNY&symbols=USD`
![screenshot-1516782376662](https://user-images.githubusercontent.com/18499887/35321995-a7e3a66a-0123-11e8-8368-d4fc8318f5d2.jpg)
执行重启...
![stop](https://user-images.githubusercontent.com/18499887/35321997-a822b67a-0123-11e8-8ef7-af5dc1c8eaa6.gif)

**Comment by shinado** [comment]
是个crash，已修复，下版本发布
