### ISSUE TITLE
关于使用Aris Launcher(China)的几个疑问

### ISSUE THREAD

**Issue by Ancientwood** [shinado/aris-open#3]
+ 能否支持 *Launch SHORTCUT* ？例如: *冰箱Ice Box*添加到桌面的*一键冻结*诸如此类的。
+ Instant Run 是否有排序功能(添加时排序无效，执行搜索前长按可*置顶*，下次搜索又恢复
+ 以及Instant Run自定义名称？(同一域名名称会重复
+ cd 组合 latest 命令失效
```
09:31:37 console.execute ->pipe://id=2014/exe=file...Fstorage..Femulated...->pipe://id=2014/exe=...latest
```
+ 最后祝老板财源广进，大吉大利(大雾坏耶

**Comment by shinado** [comment]
谢谢反馈，这些功能都还不太完善（因为没人用😂😂😂），接下来几个版本会重点完善这些功能

**Comment by Ancientwood** [comment]
各人的需求可能大不相同，感谢回复❤ *笔心* 。
此外，关于在 *酷安网友* 所说的"收到消息通知就闪回到桌面" 的确非个例，1.1.86之前未出现过此问题，目前偶尔出现。
2018祝好。

**Comment by shinado** [comment]
在吃饭，没仔细看，会解决，新年快乐！

**Comment by shinado** [comment]
Hi Ancientwood, Instant Run现在是可以自定义名称的，->add 重命名即可

**Comment by Ancientwood** [comment]
Hi shinado,不知是否是我理解错了？
![](http://owk8pz4f2.bkt.clouddn.com/201801021735_718.png)

**Comment by shinado** [comment]
Sorry, 没注意看题目，我的错😂

**Comment by shinado** [comment]
另外，可否详细讲一下你使用cd 组合 latest 命令失效的情况？

**Comment by Ancientwood** [comment]
就比如说我最常用的*打开最近拍摄的图片*：
`
cd dcim->latest
`
`
05:45:18 console.execute ->file:///storage/emulated/0/DCIM -> $#latest
`
无反应。
此外，1.1.86版本使用`cd`命令*弹出play选项*😂
![image](https://user-images.githubusercontent.com/18499887/34480037-ff7df682-efe4-11e7-8980-42bf8d941e61.png)

**Comment by shinado** [comment]
话说现在的手机拍的照片应该是在DCIM/Camera里，你试试

**Comment by Ancientwood** [comment]
不不不，与*路径无关*。（本机确认为DCIM/下
还存有一些上古版本时用的组合指令，无法使用。

**Comment by shinado** [comment]
嗯，我更新一下，好歹有个提示

**Comment by Ancientwood** [comment]
没错，在`DCIM/Camera`下*latest*生效，`DCIM/`则不...
然而我新图片的确是在`DCIM/`下😥

**Comment by shinado** [comment]
最新的可能是文件夹，所以才没反应

**Comment by Ancientwood** [comment]
确认了，正解！的确不是bug。
有一个空文件夹`Burst`才永远是最新的（大概是连续拍照的

**Comment by shinado** [comment]
OK理应要切换到那个文件夹才对，会修复的

On Jan 2, 2018 18:15, "Anc" <notifications@github.com> wrote:

确认了，正解！的确不是bug。
有一个空文件夹Burst才永远是最新的（大概是连续拍照的

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/shinado/aris-open/issues/3#issuecomment-354735655>, or mute
the thread

**Comment by Ancientwood** [comment]
看到最新版本内置了*最新照片*的功能，十分感动(虽然我的照片存储目录是在`DCIM/`根目录下😂
除了快速启动*冰箱内应用*这样的小众需求，其它类bug和feature都有所解决了，十分感谢！

**Comment by Ancientwood** [comment]
大佬，↓这不就是我说的**feature**吗↓（*生气脸*
![](https://ooo.0o0.ooo/2018/01/24/5a67e614a3bbc.jpg)
既然这周解决Bug的话...一收到通知就跳转到桌面这个锅**Aris Launcher**背了吧

**Comment by Ancientwood** [comment]
大佬，↓这不就是我想要的**启动冰箱等快捷方式**功能吗↓（*生气脸*
![](https://ooo.0o0.ooo/2018/01/24/5a67e614a3bbc.jpg)
既然这周解决Bug的话...那么...[上文](https://github.com/shinado/aris-open/issues/3#issuecomment-354599640)所说一收到通知就跳回到桌面这个锅**Aris Launcher**背了吧

**Comment by shinado** [comment]
他说的不是同一个东西吧。跳回桌面你也出现过？你的手机是什么系统？

**Comment by Ancientwood** [comment]
好吧，我的意思是能够支持快捷方式(●ˇ∀ˇ●)；系统为 国际版 Flyme 6.7.3.3G beta；

**Comment by shinado** [comment]
目前来看这个bug都出在魅族上面

**Comment by shinado** [comment]
继续甩锅

**Comment by Ancientwood** [comment]
帅锅

**Comment by Ancientwood** [comment]
其实一直在用的功能都是上古版本的功能(ง •_•)ง（考虑滚回去？

**Comment by shinado** [comment]
嗯？意思是？

**Comment by shinado** [comment]
我滚回去给你个包确认一下？

**Comment by shinado** [comment]
加我QQ吧1360911795

**Comment by shinado** [comment]
不对，要加这个45079377
