### ISSUE TITLE
关于Aris Launcher桌面对机械键盘的支持

### ISSUE THREAD

**Issue by Ancientwood** [shinado/aris-open#5]
因为平时会偶尔键盘蓝牙连接，以及电脑使用*Chrome*扩展**Vysor**操作手机，于是发现了这个问题，分两种情况：
1. **Vysor** ：
+ 敲击 Enter 无反应且无法继续输入
+ 敲击 Space 目前为指令向右👉翻一页
+ 敲击 Tab 为切换 显示/隐藏 **输入法**
2. Bluetooth 直连
+ 敲击 Enter 无反应且无法继续输入，此时敲击 Space 则为指令翻页
+ 非上诉条件敲击 Space 为正常输入空格

*emmm...又是有些奇葩的需求...*
**希望：**
+ Enter 执行第一条指令
+ Space 正常输入
+ Tab 选中下一条指令
*老板，这需求能加吗？🤐*

**Comment by shinado** [comment]
首先，我得买一个物理键盘😂

**Comment by Ancientwood** [comment]
原谅我又可耻地笑了😂

**Comment by shinado** [comment]
入手了一个蓝牙键盘，好用到哭

**Comment by shinado** [comment]
@Ancientwood 赶紧更新最新版呀

**Comment by Ancientwood** [comment]
没有解决辣鸡魅族的收到消息闪退的bug我是不会更新的_（傲娇脸_
嗯...还是等换_机吧_

**Comment by shinado** [comment]
赶紧换机_吧
